### PR TITLE
Switching to GoLangCi-Lint

### LINKED ISSUE #26: Switch to golanci-lint
gometalinter is failing on master because it changes all the time. We've had much better luck with golangci-lint.  Let's switch to using that.

### PR DESCRIPTION
**Pull request by vishakhanihore**
fixes #26

### CODE REVIEW

**Comment by vishakhanihore** [comment]
@djmitche Please check

**Comment by djmitche** [comment]
I think this will need a change in .taskcluster.yml too, as it currently runs gometalinter.

**Comment by vishakhanihore** [comment]
Making the changes right away.

**Comment by vishakhanihore** [comment]
@djmitche `Go Get` is not suitable for golangci-lint, should I write bash
curl to install golangci-lint in .taskcluster.yml

**Comment by djmitche** [comment]
Yes, you can see an example here:
```
https://github.com/taskcluster/websocktunnel/blob/master/.taskcluster.yml#L77
```

**Comment by vishakhanihore** [comment]
Are the rules setted in yml sufficient or we need some extra?

**Comment by djmitche** [comment]
I think those are fine.

**Comment by vishakhanihore** [comment]
@djmitche Made the change 😄

**Comment by vishakhanihore** [comment]
@djmitche Review

**Comment by djmitche** [comment]
This looks good!  It's not actually running in Taskcluster, but that's due to another PR that's still pending.

**Comment by vishakhanihore** [comment]
Can I write it in contribution @djmitche?
Also I needed to discuss the timeline and other application related stuff
for outreachy, where should I begin through? @helfi92

**Comment by djmitche** [comment]
Sure, you can include it as a contribution!  @helfi92 is the mentor
for the project (I'm just helping out), so I will let the two of you
communicate about the application.

**Comment by helfi92** [comment]
@vishakhanihore I will send you an email momentarily.

**Pull request merged**
