### PR TITLE
Add a bit of documentation

### PR DESCRIPTION
**Pull request by owlishDeveloper**
I've met that function! 😊

### CODE REVIEW

**Comment by djmitche** [comment]
Better to say `taskcluster-web`.  We expect that most routes will remain the same between the two.

**Comment by owlishDeveloper** [comment]
Actually, can you please explain this function a bit better? I see all it does is concatenating two strings... in our case - rootUrl and the rest... where the rest is being constructed by the caller. So, if I grab string A from config, and construct string B myself... Why do I need a separate function to do `A + B`?

**Comment by djmitche** [comment]
"Generate a URL containing a route in the taskcluster-web user interface.  This is useful for supplying clickable links to users in logs, emails, and so on."

While it's true that this is just concatenation, simply using concatenation hides the fact that this is a user-interface link (especially since there's nothing like "ui" or "taskcluster-web" in the URL).  If we know that every time we create a UI URL, it's with tc-lib-urls' `ui(..)`, then it's easy to find all such uses or even modify them.  For example if there's an XSS issue and we have to move them to a subdomain, we would want to just release a new version of tc-lib-urls and be confident that everything would just magically change.  It's a subtle point, and maybe there was no point in adding the abstraction, but since we have it it's best to be consistent about it, or we lose the (potential) benefit.

**Comment by owlishDeveloper** [comment]
(I'm probably dwelling on this too long for what it is tho. Let me just implement the requested changes, and then we all will move on with our lives 😄 )

**Comment by djmitche** [comment]
Maybe not -- perhaps the UI is always at the `ui` subdomain of the rootUrl, so we parse the rootUrl, prepend `ui.`, and reassemble.  Or something.  It was a hypothetical :)

I'll give another example: we are very consistent about using tc-lib-api to configure Express for our API services.  When we decided to change the paths at which they were served (from `/v1/foo` to `/api/serviceName/v1/foo`) we only had to change tc-lib-api, and every service reliably made the change.  Even when unused, having an airtight abstraction is a good way to make your future self's life easier.  Turning an airtight abstraction into a leaky abstraction ruins that benefit and leaves you with a cleanup of either removing the abstraction everywhere or fixing the leaks later.

**Comment by owlishDeveloper** [comment]
> When we decided to change the paths at which they were served (from /v1/foo to /api/serviceName/v1/foo) we only had to change tc-lib-api, and every service reliably made the change.
I bet that was `api` method, which is actually similar to what I'm proposing in `inspector-url` PR - a function to construct a url with a specific purpose given data needed (service name, version, root url). Imagine we had `backend()` method instead, for all things backend, which would take in two strings, root url and the rest of the url (`/v1/foo` in this example). Would switching to `/v1/foo to /api/serviceName` from `/v1/foo` be as easy in that case?

Anyways, like I said - I'm probably missing some context for this, so eventually it all will make sense as I work with all the codebase more. I'll implement the suggested changes in both the PRs! 👍

**Comment by petemoore** [comment]
The point of confusion is probably that calling `ui` function produces different results based on the base url. If you pass in the root url `https://taskcluster.net` the logic follows a different path, namely it will send you to `https://tools.taskcluster.net/<path>` rather than `https://taskcluster.net/<path>`, where as for other root urls, you will indeed be directed to `<rootURL>/<path>`. The original intention for the tc-urls package was to provide a uniform mechanism to build a url, which worked for our current `taskcluster.net` url scheme, but would also work for other redeployments, which use a slightly different url scheme. In the case of the tools site, I think we chose to avoid the convension of mapping `https://<subsystem>.taskcluster.net/<path> -> https://<new-domain>/<subsystem>/<path>`, perhaps to keep urls short. In other words, it could have been implemented as `https://tools.taskcluster.net/<path> -> https://<new-domain>/tools/<path>` but we choose to omit `/tools` in the path, perhaps for brevity, I'm not sure (@djmitche / @imbstack can advise).

So the driver for having a `ui` method is so we can just call `ui` with an arbitrary root url, and the returned url should work for both our current deployment (something like `rootURL == 'https://taskcluster.net' ? 'https://tools.taskcluster.net/${path}' : '${rootURL}/${path}'`. This should work for all valid taskcluster-web paths, regardless of the deployment they are on.

Hope this helps to untangle the mystery. :-)

**Comment by petemoore** [comment]
> Anyways, like I said - I'm probably missing some context for this, so eventually it all will make sense as I work with all the codebase more. I'll implement the suggested changes in both the PRs! 👍

It is great that you ask questions when you have doubts - don't ever be afraid to do this, so please continue to raise concerns, like you have done here, if the justifications you are getting don't make sense or aren't sufficient to dispel your concerns. Don't feel like you need to agree to keep the peace, or to accept invalid arguments. We hired you for your savvy brain, so it is great that you challenge any points that you don't agree with.

**Comment by owlishDeveloper** [comment]
Added description. Not sure what's with the tests - will look at that later

**Comment by petemoore** [comment]
> Added description. Not sure what's with the tests - will look at that later

I've added debug output to the java build/test step in e7d387e2572779c09e4a39c67a85b95787390ba9 to see if that provides more insight, as it looks like some weird crash.

**Pull request merged**
